dpbmdapp/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('notes.urls')),
    path('admin/', admin.site.urls)
]

notes/urls.py
from django.urls import path

from . import views

app_name = 'notes'
urlpatterns = [
    # task lists
    path('', views.IndexView.as_view(), name='index'),
    path('list/<int:pk>', views.TaskListView.as_view(), name='list'),
    path('addList', views.addList, name='addList'),
    path('deleteList/<int:list_id>', views.deleteList, name='deleteList'),
    path('renameList/<int:pk>', views.RenameListView.as_view(), name='renameList'),
    path('updateListName/<int:list_id>', views.updateListName, name='updateListName'),
    # tasks
    path('toggleTask/<int:tasklist_id>/<int:task_id>', views.toggleTask, name='toggleTask'),
    path('addTask/<int:tasklist_id>', views.addTask, name='addTask'),
    path('deleteTask/<int:tasklist_id>/<int:task_id>', views.deleteTask, name='deleteTask'),
    path('renameTask/<int:pk>', views.RenameTaskView.as_view(), name='renameTask'),
    path('updateTaskName/<int:task_id>', views.updateTaskText, name='updateTaskText'),
    path('addAuth', views.addAuth, name='addAuth'),
    path('verifyAuth', views.verifyAuth, name='verifyAuth')
]

notes/models.py
from django.db import models

# Create your models here.

# One TaskList can have 0 or more Tasks.
class TaskList(models.Model):
    name = models.CharField(max_length=34)

    def __str__(self):
        return self.name

# One Task belongs to one TaskList.
class Task(models.Model):
    task_list = models.ForeignKey(TaskList, on_delete=models.CASCADE)
    completed = models.BooleanField(default=False)
    text = models.CharField(max_length=120)

    def __str__(self):
        return self.text

class Auth(models.Model):
    number = models.CharField(max_length=12)

    def __str__(self):
        return self.number

notes/views.py
import os

from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.views import generic
from django.urls import reverse

from .models import Auth, Task, TaskList

from twilio.rest import Client
# Create your views here.

authyClient = Client(os.environ['AUTHY_SID'], os.environ['AUTHY_SECRET'])

# Task Lists
class IndexView(generic.ListView):
    template_name = 'notes/index.html'
    context_object_name = 'task_lists'

    def get_queryset(self):
        """
        Return all lists available.
        """
        return TaskList.objects.all()

class TaskListView(generic.DetailView):
    model = TaskList
    template_name = 'notes/list.html'

class RenameListView(generic.DetailView):
    model = TaskList
    template_name = 'notes/renameList.html'

def addList(request):
    if request.POST['newListName']:
        # this should be sanitized :(
        new_list_name = request.POST['newListName']
        if  len(new_list_name) <= TaskList._meta.get_field('name').max_length:
            l = TaskList(name=new_list_name)
            l.save()
            return HttpResponseRedirect(reverse('notes:index'))
        else:
            return render(request, 'notes/index.html', {
                'error_message': "That name is too long! (max 34 characters)",
                'task_lists': TaskList.objects.all()
            })
    else:
        return render(request, 'notes/index.html', {
            'error_message': "Please enter a name for the new list!",
            'task_lists': TaskList.objects.all()
        })

def deleteList(request, list_id):
    # user access should be checked
    l = get_object_or_404(TaskList, pk=list_id)
    l.delete()
    return HttpResponseRedirect(reverse('notes:index'))

def updateListName(request, list_id):
    if request.POST['newListName']:
        # this should be sanitized :(
        new_list_name = request.POST['newListName']
        if  len(new_list_name) <= TaskList._meta.get_field('name').max_length:
            # user access should be checked
            l = get_object_or_404(TaskList, pk=list_id)
            l.name = new_list_name
            l.save()
            return HttpResponseRedirect(reverse('notes:index'))
        else:
            return render(request, 'notes/renameList.html', {
                'error_message': "That name is too long! (max 34 characters)",
                'tasklist': get_object_or_404(TaskList, pk=list_id)
            })
    else:
        return render(request, 'notes/renameList.html', {
            'error_message': "Please enter a new list name!",
            'tasklist': get_object_or_404(TaskList, pk=list_id)
        })

# Tasks
class RenameTaskView(generic.DetailView):
    model = Task
    template_name = 'notes/renameTask.html'

def toggleTask(request, tasklist_id, task_id):
    # user access should be checked
    t = get_object_or_404(Task, pk=task_id)
    t.completed = not t.completed
    t.save()
    return HttpResponseRedirect(reverse('notes:list', args=[tasklist_id]))

def addTask(request, tasklist_id):
    if request.POST['newTaskText']:
        # this should be sanitized :(
        new_task_text = request.POST['newTaskText']
        if  len(new_task_text) <= Task._meta.get_field('text').max_length:
            # user access should be checked
            l = get_object_or_404(TaskList, pk=tasklist_id) # make sure list exists
            t = Task(task_list=l, text=new_task_text)
            t.save()
            return HttpResponseRedirect(reverse('notes:list', args=[tasklist_id]))
        else:
            return render(request, 'notes/list.html', {
                'error_message': "That is too long! (max 120 characters)",
                'tasklist': get_object_or_404(TaskList, pk=tasklist_id)
            })
    else:
        return render(request, 'notes/list.html', {
            'error_message': "Please enter some text for the new task!",
            'tasklist': get_object_or_404(TaskList, pk=tasklist_id)
        })

def deleteTask(request, tasklist_id, task_id):
    # user access should be checked
    t = get_object_or_404(Task, pk=task_id)
    t.delete()
    return HttpResponseRedirect(reverse('notes:list', args=[tasklist_id]))

def updateTaskText(request, task_id):
    print(request.POST)
    if request.POST['newTaskText']:
        # this should be sanitized :(
        new_task_text = request.POST['newTaskText']
        if  len(new_task_text) <= Task._meta.get_field('text').max_length:
            # user access should be checked
            t = get_object_or_404(Task, pk=task_id)
            t.text = new_task_text
            t.save()
            return HttpResponseRedirect(reverse('notes:list', args=[t.task_list.id]))
        else:
            return render(request, 'notes/renameTask.html', {
                'error_message': "That name is too long! (max 34 characters)",
                'task': get_object_or_404(Task, pk=task_id)
            })
    else:
        return render(request, 'notes/renameTask.html', {
            'error_message': "Please enter some text for the task!",
            'task': get_object_or_404(Task, pk=task_id)
        })

# authy
def addAuth(request):
    if request.POST['phoneNumber']:
        # this should be sanitized :(
        phone_number = request.POST['phoneNumber']
        if  len(phone_number) == 10:
            
            if Auth.objects.all():
                a = Auth.objects.get(pk=1)
                a.number = f'+1{phone_number}'
            else:
                a = Auth(number=f'+1{phone_number}')
            a.save()
            v = authyClient.verify.services(os.environ['AUTHY_SERVICE']).verifications.create(to=a.number, channel='sms')
            return render(request, 'notes/index.html', {
                'auth_message': "Authy request sent! Enter your code to verify.",
                'task_lists': TaskList.objects.all()
            })
        else:
            return render(request, 'notes/index.html', {
                'auth_message': "That is too long! Start with the area code (max 10 characters)",
                'task_lists': TaskList.objects.all()
            })
    else:
        return render(request, 'notes/index.html', {
            'auth_message': "Please enter a phone number, starting with the area code!",
            'task_lists': TaskList.objects.all()
        })

def verifyAuth(request):
    if request.POST['code']:
        # this should be sanitized :(
        code = request.POST['code']
        if  len(code) == 6:
            a = Auth.objects.get(pk=1)
            if a:
                v = authyClient.verify.services(os.environ['AUTHY_SERVICE']).verification_checks.create(to=a.number, code=code)
                return render(request, 'notes/index.html', {
                    'auth_message': f'Authy verify status: {v.status}',
                    'task_lists': TaskList.objects.all()
                })
            else:
                return render(request, 'notes/index.html', {
                    'auth_message': "Enter a phone number above first to verify.",
                    'task_lists': TaskList.objects.all()
                })
        else:
            return render(request, 'notes/index.html', {
                'auth_message': "The authy code should be 6 digits.",
                'task_lists': TaskList.objects.all()
            })

notes/templates/notes/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>DP Notes</title>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css" />
    <!-- Google Fonts Roboto -->
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap"
    />
    <!-- BS -->
    <link rel="stylesheet" href="{% static 'BS/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'notes/css/index.css' %}" />
  </head>
  <body>
    <!-- Start your project here-->
    <div class="container">
      <div class="d-flex justify-content-center align-items-center" style="height: 100vh;">
        <div class="text-center">
            <div class="new-list">
                {% if error_message %}
                  <div class="alert alert-danger" role="alert">
                    <p>{{ error_message }}</p>
                  </div>
                {% endif %}
                <form class="row row-cols-lg-auto g-3 align-items-center" action="{% url 'notes:addList' %}" method="post">
                  {% csrf_token %}
                  <div class="col-12">
                    <label class="visually-hidden" for="inlineFormInputGroupListName">listName</label>
                    <div class="input-group">
                      <div class="input-group-text">♥</div>
                      <input
                        type="text"
                        class="form-control"
                        id="inlineFormInputGroupListName"
                        placeholder="New List"
                        name='newListName'
                      />
                      <button type="submit" class="btn btn-primary">+</button>
                    </div>
                  </div>
                </form>
            </div>   
            <div class="lists">
                {% if task_lists %}
                    <ul class="list-group">
                        {% for list in task_lists %}
                            <div class="task-list-wrapper">
                              <li class="list-group-item d-flex justify-content-between align-items-center">
                                <a href="{% url 'notes:list' list.id %}"><h4 class="text-start">{{ list.name }}</h4></a>
                                <div class="btn-group" role="group" aria-label="List Buttons">
                                  <a href="{% url 'notes:renameList' list.id %}">
                                    <button type="submit" class="btn btn-warning"><i class="fas fa-edit"></i></button>
                                  </a>
                                  <form action="{% url 'notes:deleteList' list.id %}" method="post">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-danger"><i class="fas fa-trash"></i></button>
                                  </form>
                                </div>
                              </li>
                            </div>
                        {% endfor %}
                    </ul>
                {% else %}
                  <ul class="list-group">
                    <li class="list-group-item d-flex justify-content-center align-items-center">
                      No lists are available.
                    </li>
                  </ul>
                {% endif %}
            </div>
            <br>
            <ul class="list-group">
              <h2> Authy </h2>
              <li class="list-group-item d-flex justify-content-between align-items-center">
                <form class="row row-cols-lg-auto g-3 align-items-center" action="{% url 'notes:addAuth' %}" method="post">
                  {% csrf_token %}
                  <div class="input-group">
                    <div class="input-group-text">phone number</div>
                    <input
                      type="text"
                      class="form-control"
                      id="inlineFormInputGroupListName"
                      placeholder="8001234567"
                      name='phoneNumber'
                    />
                    <button type="submit" class="btn btn-primary">Get Code</button>
                  </div>
                </form>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center">
                <form class="row row-cols-lg-auto g-3 align-items-center" action="{% url 'notes:verifyAuth' %}" method="post">
                  {% csrf_token %}
                  <div class="input-group">
                    <div class="input-group-text">Code</div>
                    <input
                      type="text"
                      class="form-control"
                      id="inlineFormInputGroupListName"
                      placeholder="123456"
                      name='code'
                    />
                    <button type="submit" class="btn btn-primary">Verify</button>
                  </div>
                </form>
              </li>
              {% if auth_message %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                  <div class="alert alert-primary" role="alert">
                    <p>{{ auth_message }}</p>
                  </div>
                </li>
              {% endif %}
        </div>
      </div>
    </div>
    <!-- End your project here-->

    <!-- BS -->
    <script type="text/javascript" src="{% static 'BS/js/bootstrap.min.js' %}"></script>
    <!-- Custom scripts -->
    <script type="text/javascript"></script>
  </body>
</html>

notes/templates/notes/list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>DP Notes</title>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css" />
    <!-- Google Fonts Roboto -->
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap"
    />
    <!-- BS -->
    <link rel="stylesheet" href="{% static 'BS/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'notes/css/index.css' %}" />
  </head>
    <!-- Start your project here-->
    <div class="container">
      <div class="d-flex justify-content-center align-items-center" style="height: 100vh;">
        <div class="text-center">
            <h1>{{ tasklist.name }}</h1>
            <div class="new-list">
                {% if error_message %}
                    <div class="alert alert-danger" role="alert">
                        <p>{{ error_message }}</p>
                    </div>
                {% endif %}
                <form class="row row-cols-lg-auto g-3 align-items-center" action="{% url 'notes:addTask' tasklist.id %}" method="post">
                    {% csrf_token %}
                    <div class="col-12">
                        <label class="visually-hidden" for="inlineFormInputGroupTaskText">taskText</label>
                        <div class="input-group">
                            <a class="input-group-text" href="{% url 'notes:index' %}"><i class="fas fa-arrow-left"></i></a>
                            <input
                            type="text"
                            class="form-control"
                            id="inlineFormInputGroupTaskText"
                            placeholder="New Task"
                            name='newTaskText'
                            />
                            <button type="submit" class="btn btn-primary">+</button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="tasks">    
                {% if tasklist.task_set.all %}
                <ul class="list-group">
                        {% for task in tasklist.task_set.all %}
                        <div class=task-wrapper>
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                {{ task.text }}
                                <div class="btn-group" role="group" aria-label="Task Buttons">
                                    <form action="{% url 'notes:toggleTask' tasklist.id task.id %}" method="post">
                                        {% csrf_token %}
                                        {% if task.completed %}
                                            <button type="submit" class="btn btn-success"><i class="fas fa-check"></i></button>
                                        {% else %}
                                            <button type="submit" class="btn btn-secondary"><i class="fas fa-hourglass-half"></i></button>
                                        {% endif %}
                                    </form>
                                    <a href="{% url 'notes:renameTask' task.id %}">
                                        <button type="submit" class="btn btn-warning"><i class="fas fa-edit"></i></button>
                                    </a>
                                    <form action="{% url 'notes:deleteTask' tasklist.id task.id %}" method="post">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-danger"><i class="fas fa-trash"></i></button>
                                    </form>
                                </div>
                            </li>
                        </div>
                        {% endfor %}
                    </ul>
                {% else %}
                <ul class="list-group">
                    <li class="list-group-item d-flex justify-content-center align-items-center">
                      No tasks are available.
                    </li>
                  </ul>
                {% endif %}
            </div>
        </div>
      </div>
    </div>
    <!-- End your project here-->

    <!-- BS -->
    <script type="text/javascript" src="{% static 'BS/js/bootstrap.min.js' %}"></script>
    <!-- Custom scripts -->
    <script type="text/javascript"></script>
  </body>
</html>

notes/templates/notes/renameList.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>DP Notes</title>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css" />
    <!-- Google Fonts Roboto -->
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap"
    />
    <!-- BS -->
    <link rel="stylesheet" href="{% static 'BS/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'notes/css/index.css' %}" />
  </head>
  <body>
    <!-- Start your project here-->
    <div class="container">
      <div class="d-flex justify-content-center align-items-center" style="height: 100vh;">
        <div class="text-center">
            <div class="rename-list">
                <h1>Please enter a new name for {{ tasklist.name }}:</h1>
                <form class="row row-cols-lg-auto g-3 align-items-center" action="{% url 'notes:updateListName' tasklist.id %}" method="post">
                    {% csrf_token %}
                    <div class="col-12">
                      <label class="visually-hidden" for="inlineFormInputGroupListName">listName</label>
                      <div class="input-group">
                        <div class="input-group-text">♥</div>
                        <input
                          type="text"
                          class="form-control"
                          id="inlineFormInputGroupListName"
                          placeholder="New Name"
                          name='newListName'
                        />
                      </div>
                    </div>
                    <div class="col-12">
                        <button type="submit" class="btn btn-primary">Rename</button>
                    </div>
                </form>
            </div>
            {% if error_message %}
              <div class="alert alert-danger" role="alert">
                <p>{{ error_message }}</p>
              </div>
            {% endif %}
        </div>
      </div>
    </div>
    <!-- End your project here-->

    <!-- BS -->
    <script type="text/javascript" src="{% static 'BS/js/bootstrap.min.js' %}"></script>
    <!-- Custom scripts -->
    <script type="text/javascript"></script>
  </body>
</html>

notes/templates/notes/renameTask.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>DP Notes</title>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css" />
    <!-- Google Fonts Roboto -->
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap"
    />
    <!-- BS -->
    <link rel="stylesheet" href="{% static 'BS/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'notes/css/index.css' %}" />
  </head>
  <body>
    <!-- Start your project here-->
    <div class="container">
      <div class="d-flex justify-content-center align-items-center" style="height: 100vh;">
        <div class="text-center">
            <div class="rename-list">
                <h1> Please modify the text below:</h1>
                <form class="row row-cols-lg-auto g-3 align-items-center" action="{% url 'notes:updateTaskText' task.id %}" method="post">
                    {% csrf_token %}
                    <div class="col-12">
                      <textarea class="form-control" name='newTaskText'>{{ task.text }}</textarea>
                    </div>
                    <div class="col-12">
                      <button type="submit" class="btn btn-primary">Update</button>
                    </div>
                </form>
            </div>
            {% if error_message %}
              <div class="alert alert-danger" role="alert">
                <p>{{ error_message }}</p>
              </div>
            {% endif %}
        </div>
      </div>
    </div>
    <!-- End your project here-->

    <!-- BS -->
    <script type="text/javascript" src="{% static 'BS/js/bootstrap.min.js' %}"></script>
    <!-- Custom scripts -->
    <script type="text/javascript"></script>
  </body>
</html>